/*
 * Created on Apr 14, 2010
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *
 * Copyright @2010 the original author or authors.
 */
package org.fest.keyboard.mapping;

/**
 * Understands an "About" dialog.
 *
 * @author Alex Ruiz
 */
public class AboutDialog extends javax.swing.JDialog {

  private static final long serialVersionUID = 1L;

  /**
   * Creates a new </code>{@link AboutDialog}</code>.
   * @param parent the parent frame.
   * @param modal indicates whether the dialog should be modal or not.
   */
  public AboutDialog(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    aboutLabel = new javax.swing.JLabel();
    closeButton = new javax.swing.JButton();
    logoLabel = new javax.swing.JLabel();

    setTitle("About");
    setModal(true);
    setName("aboutDialog"); // NOI18N
    setResizable(false);

    aboutLabel.setText("<html> <strong>FEST Keyboard Mapping Tool</strong> <p> Copyright @2010 FEST<br/> (Fixtures for Easy Software Testing)<br/></p> <p> http://fest.easytesting.org </p> </html>");
    aboutLabel.setName("aboutLabel"); // NOI18N

    closeButton.setMnemonic('C');
    closeButton.setText("Close");
    closeButton.setName("closeButton"); // NOI18N
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeWindow(evt);
      }
    });

    logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fest64.png"))); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(logoLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGap(106, 106, 106)
            .addComponent(closeButton)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(aboutLabel)
          .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(closeButton)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    aboutLabel.getAccessibleContext().setAccessibleName("aboutLabel");

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void closeWindow(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeWindow
    setVisible(false);
  }//GEN-LAST:event_closeWindow

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel aboutLabel;
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel logoLabel;
  // End of variables declaration//GEN-END:variables

}
